package Serialization.Encoder.Protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: column.proto

// Protobuf Java Version: 3.25.1
public final class ColumnOuterClass {
  private ColumnOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ColumnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Column)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
     */
    boolean containsData(
        java.lang.String key);
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.ListValue>
    getData();
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.ListValue>
    getDataMap();
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
     */
    /* nullable */
com.google.protobuf.ListValue getDataOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.ListValue defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
     */
    com.google.protobuf.ListValue getDataOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code Column}
   */
  public static final class Column extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Column)
      ColumnOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Column.newBuilder() to construct.
    private Column(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Column() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Column();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ColumnOuterClass.internal_static_Column_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ColumnOuterClass.internal_static_Column_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ColumnOuterClass.Column.class, ColumnOuterClass.Column.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private static final class DataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.ListValue> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.ListValue>newDefaultInstance(
                  ColumnOuterClass.internal_static_Column_DataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.ListValue.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ListValue> data_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ListValue>
    internalGetData() {
      if (data_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      return data_;
    }
    public int getDataCount() {
      return internalGetData().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
     */
    @java.lang.Override
    public boolean containsData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ListValue> getData() {
      return getDataMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.protobuf.ListValue> getDataMap() {
      return internalGetData().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.ListValue getDataOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.ListValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ListValue> map =
          internalGetData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ListValue getDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ListValue> map =
          internalGetData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetData(),
          DataDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ListValue> entry
           : internalGetData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ListValue>
        data__ = DataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, data__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ColumnOuterClass.Column)) {
        return super.equals(obj);
      }
      ColumnOuterClass.Column other = (ColumnOuterClass.Column) obj;

      if (!internalGetData().equals(
          other.internalGetData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetData().getMap().isEmpty()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ColumnOuterClass.Column parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ColumnOuterClass.Column parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ColumnOuterClass.Column parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ColumnOuterClass.Column parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ColumnOuterClass.Column parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ColumnOuterClass.Column parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ColumnOuterClass.Column parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ColumnOuterClass.Column parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ColumnOuterClass.Column parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ColumnOuterClass.Column parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ColumnOuterClass.Column parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ColumnOuterClass.Column parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ColumnOuterClass.Column prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Column}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Column)
        ColumnOuterClass.ColumnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ColumnOuterClass.internal_static_Column_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ColumnOuterClass.internal_static_Column_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ColumnOuterClass.Column.class, ColumnOuterClass.Column.Builder.class);
      }

      // Construct using ColumnOuterClass.Column.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableData().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ColumnOuterClass.internal_static_Column_descriptor;
      }

      @java.lang.Override
      public ColumnOuterClass.Column getDefaultInstanceForType() {
        return ColumnOuterClass.Column.getDefaultInstance();
      }

      @java.lang.Override
      public ColumnOuterClass.Column build() {
        ColumnOuterClass.Column result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ColumnOuterClass.Column buildPartial() {
        ColumnOuterClass.Column result = new ColumnOuterClass.Column(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ColumnOuterClass.Column result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.data_ = internalGetData().build(DataDefaultEntryHolder.defaultEntry);
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ColumnOuterClass.Column) {
          return mergeFrom((ColumnOuterClass.Column)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ColumnOuterClass.Column other) {
        if (other == ColumnOuterClass.Column.getDefaultInstance()) return this;
        internalGetMutableData().mergeFrom(
            other.internalGetData());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ListValue>
                data__ = input.readMessage(
                    DataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableData().ensureBuilderMap().put(
                    data__.getKey(), data__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private static final class DataConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.google.protobuf.ListValueOrBuilder, com.google.protobuf.ListValue> {
        @java.lang.Override
        public com.google.protobuf.ListValue build(com.google.protobuf.ListValueOrBuilder val) {
          if (val instanceof com.google.protobuf.ListValue) { return (com.google.protobuf.ListValue) val; }
          return ((com.google.protobuf.ListValue.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ListValue> defaultEntry() {
          return DataDefaultEntryHolder.defaultEntry;
        }
      };
      private static final DataConverter dataConverter = new DataConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.String, com.google.protobuf.ListValueOrBuilder, com.google.protobuf.ListValue, com.google.protobuf.ListValue.Builder> data_;
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.protobuf.ListValueOrBuilder, com.google.protobuf.ListValue, com.google.protobuf.ListValue.Builder>
          internalGetData() {
        if (data_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(dataConverter);
        }
        return data_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.protobuf.ListValueOrBuilder, com.google.protobuf.ListValue, com.google.protobuf.ListValue.Builder>
          internalGetMutableData() {
        if (data_ == null) {
          data_ = new com.google.protobuf.MapFieldBuilder<>(dataConverter);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return data_;
      }
      public int getDataCount() {
        return internalGetData().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
       */
      @java.lang.Override
      public boolean containsData(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetData().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getDataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ListValue> getData() {
        return getDataMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.google.protobuf.ListValue> getDataMap() {
        return internalGetData().getImmutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
com.google.protobuf.ListValue getDataOrDefault(
          java.lang.String key,
          /* nullable */
com.google.protobuf.ListValue defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.ListValueOrBuilder> map = internalGetMutableData().ensureBuilderMap();
        return map.containsKey(key) ? dataConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ListValue getDataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.ListValueOrBuilder> map = internalGetMutableData().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return dataConverter.build(map.get(key));
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableData().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
       */
      public Builder removeData(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableData().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ListValue>
          getMutableData() {
        bitField0_ |= 0x00000001;
        return internalGetMutableData().ensureMessageMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
       */
      public Builder putData(
          java.lang.String key,
          com.google.protobuf.ListValue value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableData().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
       */
      public Builder putAllData(
          java.util.Map<java.lang.String, com.google.protobuf.ListValue> values) {
        for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ListValue> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableData().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.ListValue&gt; data = 1;</code>
       */
      public com.google.protobuf.ListValue.Builder putDataBuilderIfAbsent(
          java.lang.String key) {
        java.util.Map<java.lang.String, com.google.protobuf.ListValueOrBuilder> builderMap = internalGetMutableData().ensureBuilderMap();
        com.google.protobuf.ListValueOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = com.google.protobuf.ListValue.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof com.google.protobuf.ListValue) {
          entry = ((com.google.protobuf.ListValue) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (com.google.protobuf.ListValue.Builder) entry;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Column)
    }

    // @@protoc_insertion_point(class_scope:Column)
    private static final ColumnOuterClass.Column DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ColumnOuterClass.Column();
    }

    public static ColumnOuterClass.Column getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Column>
        PARSER = new com.google.protobuf.AbstractParser<Column>() {
      @java.lang.Override
      public Column parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Column> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Column> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ColumnOuterClass.Column getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Column_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Column_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Column_DataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Column_DataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014column.proto\032\037google/protobuf/timestam" +
      "p.proto\032\034google/protobuf/struct.proto\"r\n" +
      "\006Column\022\037\n\004data\030\001 \003(\0132\021.Column.DataEntry" +
      "\032G\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(" +
      "\0132\032.google.protobuf.ListValue:\0028\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_Column_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Column_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Column_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_Column_DataEntry_descriptor =
      internal_static_Column_descriptor.getNestedTypes().get(0);
    internal_static_Column_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Column_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
